### ISSUE TITLE
NIC Kext doesnt work

### ISSUE THREAD

**Issue by mitucsaki** [midi1996/VoodooGUIDES#2]
Hey I have a z97 gaming 3 mobo. I added the AtherosE2200Ethernet.kext from the repo and rebooted. but the NIC never got anything and there was no connection

I checked online and downloaded a new version of the kext which works for my mobo (killer) based on other users online. But that also doesn't work. Any suggestions?

**Comment by midi1996** [comment]
That means it's not the kext to go with? Look in windows device manager and not the internet. And if it still doesnt work, open an issue on the kext's repo or a post in its forum post.

**Comment by mitucsaki** [comment]
I tried other kexts. I fixed it by finding some forum where someone posted a custom v2.2.0 kext for E2200. My PC saw it and I got internet connection.

**Comment by midi1996** [comment]
Congrats, good for you :)
