### ISSUE TITLE
Disk does not use GUID partition

### ISSUE THREAD

**Issue by mitucsaki** [midi1996/VoodooGUIDES#3]
Hi I got to the step where I am ready to install the OS. In disk utility, I formatted an SSD I want to use, to Mac journaled, however in the install step I cannot pick this SSD and it says the disk does not use GUID partitioning. The partition button is grayed out in Disk Utility. How do I select what type of partitioning I want, I think it's doing MBR right now.

**Comment by midi1996** [comment]
check multiboot guide.

**Comment by mitucsaki** [comment]
That doesn't help me I want to use one disk, with only MacOS on it. The disk i have right now is formatted and has nothing on it. How do i format GUID without a mac?
