### ISSUE TITLE
are Realtek USB wireless cards compatible? 

### ISSUE THREAD

**Issue by chippinganimal** [midi1996/VoodooGUIDES#4]
So my pc that Id like to convert into a hackintosh is too far away from the router to run an ethernet cable (and i dont have any cat6 run through my walls, the house is very old) but I do have a Netgear A6210 wireless USB dongle that uses the Mediatek MT7610U chipset, and works great in windows 10, but do you know of any kexts that will make it work in the OSX installer? In my limited searching, I could only find full installer DMGs to use on an already installed version of Mac OS X. I will also try using my old rooted android as an internet connection if it doesnt exist. 
Thanks in advance

**Comment by midi1996** [comment]
No usb wifi will ever work, use android as a wifi to usb tethering device if you have one.
